version: '3.8'

services:
  # Redis服务
  redis:
    image: redis:7-alpine
    container_name: voimid-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - voimid-network
    restart: unless-stopped

  # PostgreSQL数据库
  postgres:
    image: postgres:15-alpine
    container_name: voimid-postgres
    environment:
      POSTGRES_DB: voimid
      POSTGRES_USER: voimid
      POSTGRES_PASSWORD: voimid_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - voimid-network
    restart: unless-stopped

  # Edge-VoMID主服务
  voimid:
    build: .
    container_name: voimid-main
    environment:
      - VOIMID_ENVIRONMENT=production
      - VOIMID_STORAGE_TYPE=redis
      - VOIMID_REDIS_HOST=redis
      - VOIMID_REDIS_PORT=6379
      - VOIMID_DB_HOST=postgres
      - VOIMID_DB_USER=voimid
      - VOIMID_DB_PASSWORD=voimid_password
      - VOIMID_DB_NAME=voimid
      - VOIMID_API_HOST=0.0.0.0
      - VOIMID_API_PORT=8080
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./models:/app/models
    depends_on:
      - redis
      - postgres
    networks:
      - voimid-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Nginx负载均衡器
  nginx:
    image: nginx:alpine
    container_name: voimid-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - voimid
    networks:
      - voimid-network
    restart: unless-stopped

  # 监控服务 (Prometheus)
  prometheus:
    image: prom/prometheus:latest
    container_name: voimid-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - voimid-network
    restart: unless-stopped

  # 监控服务 (Grafana)
  grafana:
    image: grafana/grafana:latest
    container_name: voimid-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - voimid-network
    restart: unless-stopped

volumes:
  redis_data:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  voimid-network:
    driver: bridge
